sudo: required
services:
  - docker

before_install:
  - docker build -t clflowers5/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI="true" clflowers5/docker-react npm run test -- --coverage
