sudo: required
services:
  - docker

before_install:
  - docker build -t clflowers5/docker-react -f Dockerfile.dev .

env:
  - CI=true

script:
  - docker run clflowers5/docker-react npm run test -- --coverage --forceExit
  